#include "key.h"
#include "events.h"

cogui::key cogui::key::Ctrl_Alt_A( {cogui::events::key_class::key_a, true, false, true, L"Ctrl-Alt-a"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_A>::press = cogui::key::Ctrl_Alt_A;
cogui::key cogui::key::Ctrl_Alt_B( {cogui::events::key_class::key_b, true, false, true, L"Ctrl-Alt-b"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_B>::press = cogui::key::Ctrl_Alt_B;
cogui::key cogui::key::Ctrl_Alt_C( {cogui::events::key_class::key_c, true, false, true, L"Ctrl-Alt-c"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_C>::press = cogui::key::Ctrl_Alt_C;
cogui::key cogui::key::Ctrl_Alt_D( {cogui::events::key_class::key_d, true, false, true, L"Ctrl-Alt-d"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_D>::press = cogui::key::Ctrl_Alt_D;
cogui::key cogui::key::Ctrl_Alt_E( {cogui::events::key_class::key_e, true, false, true, L"Ctrl-Alt-e"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_E>::press = cogui::key::Ctrl_Alt_E;
cogui::key cogui::key::Ctrl_Alt_F( {cogui::events::key_class::key_f, true, false, true, L"Ctrl-Alt-f"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F>::press = cogui::key::Ctrl_Alt_F;
cogui::key cogui::key::Ctrl_Alt_G( {cogui::events::key_class::key_g, true, false, true, L"Ctrl-Alt-g"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_G>::press = cogui::key::Ctrl_Alt_G;
cogui::key cogui::key::Ctrl_Alt_H( {cogui::events::key_class::key_h, true, false, true, L"Ctrl-Alt-h"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_H>::press = cogui::key::Ctrl_Alt_H;
cogui::key cogui::key::Ctrl_Alt_I( {cogui::events::key_class::key_i, true, false, true, L"Ctrl-Alt-i"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_I>::press = cogui::key::Ctrl_Alt_I;
cogui::key cogui::key::Ctrl_Alt_J( {cogui::events::key_class::key_j, true, false, true, L"Ctrl-Alt-j"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_J>::press = cogui::key::Ctrl_Alt_J;
cogui::key cogui::key::Ctrl_Alt_K( {cogui::events::key_class::key_k, true, false, true, L"Ctrl-Alt-k"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_K>::press = cogui::key::Ctrl_Alt_K;
cogui::key cogui::key::Ctrl_Alt_L( {cogui::events::key_class::key_l, true, false, true, L"Ctrl-Alt-l"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_L>::press = cogui::key::Ctrl_Alt_L;
cogui::key cogui::key::Ctrl_Alt_M( {cogui::events::key_class::key_m, true, false, true, L"Ctrl-Alt-m"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_M>::press = cogui::key::Ctrl_Alt_M;
cogui::key cogui::key::Ctrl_Alt_N( {cogui::events::key_class::key_n, true, false, true, L"Ctrl-Alt-n"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_N>::press = cogui::key::Ctrl_Alt_N;
cogui::key cogui::key::Ctrl_Alt_O( {cogui::events::key_class::key_o, true, false, true, L"Ctrl-Alt-o"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_O>::press = cogui::key::Ctrl_Alt_O;
cogui::key cogui::key::Ctrl_Alt_P( {cogui::events::key_class::key_p, true, false, true, L"Ctrl-Alt-p"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_P>::press = cogui::key::Ctrl_Alt_P;
cogui::key cogui::key::Ctrl_Alt_Q( {cogui::events::key_class::key_q, true, false, true, L"Ctrl-Alt-q"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Q>::press = cogui::key::Ctrl_Alt_Q;
cogui::key cogui::key::Ctrl_Alt_R( {cogui::events::key_class::key_r, true, false, true, L"Ctrl-Alt-r"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_R>::press = cogui::key::Ctrl_Alt_R;
cogui::key cogui::key::Ctrl_Alt_S( {cogui::events::key_class::key_s, true, false, true, L"Ctrl-Alt-s"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_S>::press = cogui::key::Ctrl_Alt_S;
cogui::key cogui::key::Ctrl_Alt_T( {cogui::events::key_class::key_t, true, false, true, L"Ctrl-Alt-t"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_T>::press = cogui::key::Ctrl_Alt_T;
cogui::key cogui::key::Ctrl_Alt_U( {cogui::events::key_class::key_u, true, false, true, L"Ctrl-Alt-u"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_U>::press = cogui::key::Ctrl_Alt_U;
cogui::key cogui::key::Ctrl_Alt_V( {cogui::events::key_class::key_v, true, false, true, L"Ctrl-Alt-v"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_V>::press = cogui::key::Ctrl_Alt_V;
cogui::key cogui::key::Ctrl_Alt_W( {cogui::events::key_class::key_w, true, false, true, L"Ctrl-Alt-w"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_W>::press = cogui::key::Ctrl_Alt_W;
cogui::key cogui::key::Ctrl_Alt_X( {cogui::events::key_class::key_x, true, false, true, L"Ctrl-Alt-x"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_X>::press = cogui::key::Ctrl_Alt_X;
cogui::key cogui::key::Ctrl_Alt_Y( {cogui::events::key_class::key_y, true, false, true, L"Ctrl-Alt-y"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Y>::press = cogui::key::Ctrl_Alt_Y;
cogui::key cogui::key::Ctrl_Alt_Z( {cogui::events::key_class::key_z, true, false, true, L"Ctrl-Alt-z"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Z>::press = cogui::key::Ctrl_Alt_Z;
cogui::key cogui::key::Alt_A( {cogui::events::key_class::key_a, true, false, false, L"Alt-a"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_A>::press = cogui::key::Alt_A;
cogui::key cogui::key::Alt_B( {cogui::events::key_class::key_b, true, false, false, L"Alt-b"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_B>::press = cogui::key::Alt_B;
cogui::key cogui::key::Alt_C( {cogui::events::key_class::key_c, true, false, false, L"Alt-c"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_C>::press = cogui::key::Alt_C;
cogui::key cogui::key::Alt_D( {cogui::events::key_class::key_d, true, false, false, L"Alt-d"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_D>::press = cogui::key::Alt_D;
cogui::key cogui::key::Alt_E( {cogui::events::key_class::key_e, true, false, false, L"Alt-e"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_E>::press = cogui::key::Alt_E;
cogui::key cogui::key::Alt_F( {cogui::events::key_class::key_f, true, false, false, L"Alt-f"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F>::press = cogui::key::Alt_F;
cogui::key cogui::key::Alt_G( {cogui::events::key_class::key_g, true, false, false, L"Alt-g"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_G>::press = cogui::key::Alt_G;
cogui::key cogui::key::Alt_H( {cogui::events::key_class::key_h, true, false, false, L"Alt-h"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_H>::press = cogui::key::Alt_H;
cogui::key cogui::key::Alt_I( {cogui::events::key_class::key_i, true, false, false, L"Alt-i"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_I>::press = cogui::key::Alt_I;
cogui::key cogui::key::Alt_J( {cogui::events::key_class::key_j, true, false, false, L"Alt-j"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_J>::press = cogui::key::Alt_J;
cogui::key cogui::key::Alt_K( {cogui::events::key_class::key_k, true, false, false, L"Alt-k"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_K>::press = cogui::key::Alt_K;
cogui::key cogui::key::Alt_L( {cogui::events::key_class::key_l, true, false, false, L"Alt-l"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_L>::press = cogui::key::Alt_L;
cogui::key cogui::key::Alt_M( {cogui::events::key_class::key_m, true, false, false, L"Alt-m"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_M>::press = cogui::key::Alt_M;
cogui::key cogui::key::Alt_N( {cogui::events::key_class::key_n, true, false, false, L"Alt-n"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_N>::press = cogui::key::Alt_N;
cogui::key cogui::key::Alt_O( {cogui::events::key_class::key_o, true, false, false, L"Alt-o"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_O>::press = cogui::key::Alt_O;
cogui::key cogui::key::Alt_P( {cogui::events::key_class::key_p, true, false, false, L"Alt-p"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_P>::press = cogui::key::Alt_P;
cogui::key cogui::key::Alt_Q( {cogui::events::key_class::key_q, true, false, false, L"Alt-q"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_Q>::press = cogui::key::Alt_Q;
cogui::key cogui::key::Alt_R( {cogui::events::key_class::key_r, true, false, false, L"Alt-r"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_R>::press = cogui::key::Alt_R;
cogui::key cogui::key::Alt_S( {cogui::events::key_class::key_s, true, false, false, L"Alt-s"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_S>::press = cogui::key::Alt_S;
cogui::key cogui::key::Alt_T( {cogui::events::key_class::key_t, true, false, false, L"Alt-t"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_T>::press = cogui::key::Alt_T;
cogui::key cogui::key::Alt_U( {cogui::events::key_class::key_u, true, false, false, L"Alt-u"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_U>::press = cogui::key::Alt_U;
cogui::key cogui::key::Alt_V( {cogui::events::key_class::key_v, true, false, false, L"Alt-v"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_V>::press = cogui::key::Alt_V;
cogui::key cogui::key::Alt_W( {cogui::events::key_class::key_w, true, false, false, L"Alt-w"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_W>::press = cogui::key::Alt_W;
cogui::key cogui::key::Alt_X( {cogui::events::key_class::key_x, true, false, false, L"Alt-x"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_X>::press = cogui::key::Alt_X;
cogui::key cogui::key::Alt_Y( {cogui::events::key_class::key_y, true, false, false, L"Alt-y"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_Y>::press = cogui::key::Alt_Y;
cogui::key cogui::key::Alt_Z( {cogui::events::key_class::key_z, true, false, false, L"Alt-z"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_Z>::press = cogui::key::Alt_Z;
cogui::key cogui::key::Ctrl_A( {cogui::events::key_class::key_a, false, false, true, L"Ctrl-a"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_A>::press = cogui::key::Ctrl_A;
cogui::key cogui::key::Ctrl_B( {cogui::events::key_class::key_b, false, false, true, L"Ctrl-b"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_B>::press = cogui::key::Ctrl_B;
cogui::key cogui::key::Ctrl_C( {cogui::events::key_class::key_c, false, false, true, L"Ctrl-c"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_C>::press = cogui::key::Ctrl_C;
cogui::key cogui::key::Ctrl_D( {cogui::events::key_class::key_d, false, false, true, L"Ctrl-d"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_D>::press = cogui::key::Ctrl_D;
cogui::key cogui::key::Ctrl_E( {cogui::events::key_class::key_e, false, false, true, L"Ctrl-e"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_E>::press = cogui::key::Ctrl_E;
cogui::key cogui::key::Ctrl_F( {cogui::events::key_class::key_f, false, false, true, L"Ctrl-f"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F>::press = cogui::key::Ctrl_F;
cogui::key cogui::key::Ctrl_G( {cogui::events::key_class::key_g, false, false, true, L"Ctrl-g"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_G>::press = cogui::key::Ctrl_G;
cogui::key cogui::key::Ctrl_H( {cogui::events::key_class::key_h, false, false, true, L"Ctrl-h"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_H>::press = cogui::key::Ctrl_H;
cogui::key cogui::key::Ctrl_I( {cogui::events::key_class::key_i, false, false, true, L"Ctrl-i"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_I>::press = cogui::key::Ctrl_I;
cogui::key cogui::key::Ctrl_J( {cogui::events::key_class::key_j, false, false, true, L"Ctrl-j"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_J>::press = cogui::key::Ctrl_J;
cogui::key cogui::key::Ctrl_K( {cogui::events::key_class::key_k, false, false, true, L"Ctrl-k"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_K>::press = cogui::key::Ctrl_K;
cogui::key cogui::key::Ctrl_L( {cogui::events::key_class::key_l, false, false, true, L"Ctrl-l"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_L>::press = cogui::key::Ctrl_L;
cogui::key cogui::key::Ctrl_M( {cogui::events::key_class::key_m, false, false, true, L"Ctrl-m"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_M>::press = cogui::key::Ctrl_M;
cogui::key cogui::key::Ctrl_N( {cogui::events::key_class::key_n, false, false, true, L"Ctrl-n"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_N>::press = cogui::key::Ctrl_N;
cogui::key cogui::key::Ctrl_O( {cogui::events::key_class::key_o, false, false, true, L"Ctrl-o"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_O>::press = cogui::key::Ctrl_O;
cogui::key cogui::key::Ctrl_P( {cogui::events::key_class::key_p, false, false, true, L"Ctrl-p"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_P>::press = cogui::key::Ctrl_P;
cogui::key cogui::key::Ctrl_Q( {cogui::events::key_class::key_q, false, false, true, L"Ctrl-q"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Q>::press = cogui::key::Ctrl_Q;
cogui::key cogui::key::Ctrl_R( {cogui::events::key_class::key_r, false, false, true, L"Ctrl-r"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_R>::press = cogui::key::Ctrl_R;
cogui::key cogui::key::Ctrl_S( {cogui::events::key_class::key_s, false, false, true, L"Ctrl-s"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_S>::press = cogui::key::Ctrl_S;
cogui::key cogui::key::Ctrl_T( {cogui::events::key_class::key_t, false, false, true, L"Ctrl-t"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_T>::press = cogui::key::Ctrl_T;
cogui::key cogui::key::Ctrl_U( {cogui::events::key_class::key_u, false, false, true, L"Ctrl-u"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_U>::press = cogui::key::Ctrl_U;
cogui::key cogui::key::Ctrl_V( {cogui::events::key_class::key_v, false, false, true, L"Ctrl-v"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_V>::press = cogui::key::Ctrl_V;
cogui::key cogui::key::Ctrl_W( {cogui::events::key_class::key_w, false, false, true, L"Ctrl-w"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_W>::press = cogui::key::Ctrl_W;
cogui::key cogui::key::Ctrl_X( {cogui::events::key_class::key_x, false, false, true, L"Ctrl-x"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_X>::press = cogui::key::Ctrl_X;
cogui::key cogui::key::Ctrl_Y( {cogui::events::key_class::key_y, false, false, true, L"Ctrl-y"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Y>::press = cogui::key::Ctrl_Y;
cogui::key cogui::key::Ctrl_Z( {cogui::events::key_class::key_z, false, false, true, L"Ctrl-z"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Z>::press = cogui::key::Ctrl_Z;
cogui::key cogui::key::A( {cogui::events::key_class::key_a, false, false, false, L"a"} );
template<> cogui::key& cogui::on<&cogui::key::A>::press = cogui::key::A;
cogui::key cogui::key::B( {cogui::events::key_class::key_b, false, false, false, L"b"} );
template<> cogui::key& cogui::on<&cogui::key::B>::press = cogui::key::B;
cogui::key cogui::key::C( {cogui::events::key_class::key_c, false, false, false, L"c"} );
template<> cogui::key& cogui::on<&cogui::key::C>::press = cogui::key::C;
cogui::key cogui::key::D( {cogui::events::key_class::key_d, false, false, false, L"d"} );
template<> cogui::key& cogui::on<&cogui::key::D>::press = cogui::key::D;
cogui::key cogui::key::E( {cogui::events::key_class::key_e, false, false, false, L"e"} );
template<> cogui::key& cogui::on<&cogui::key::E>::press = cogui::key::E;
cogui::key cogui::key::F( {cogui::events::key_class::key_f, false, false, false, L"f"} );
template<> cogui::key& cogui::on<&cogui::key::F>::press = cogui::key::F;
cogui::key cogui::key::G( {cogui::events::key_class::key_g, false, false, false, L"g"} );
template<> cogui::key& cogui::on<&cogui::key::G>::press = cogui::key::G;
cogui::key cogui::key::H( {cogui::events::key_class::key_h, false, false, false, L"h"} );
template<> cogui::key& cogui::on<&cogui::key::H>::press = cogui::key::H;
cogui::key cogui::key::I( {cogui::events::key_class::key_i, false, false, false, L"i"} );
template<> cogui::key& cogui::on<&cogui::key::I>::press = cogui::key::I;
cogui::key cogui::key::J( {cogui::events::key_class::key_j, false, false, false, L"j"} );
template<> cogui::key& cogui::on<&cogui::key::J>::press = cogui::key::J;
cogui::key cogui::key::K( {cogui::events::key_class::key_k, false, false, false, L"k"} );
template<> cogui::key& cogui::on<&cogui::key::K>::press = cogui::key::K;
cogui::key cogui::key::L( {cogui::events::key_class::key_l, false, false, false, L"l"} );
template<> cogui::key& cogui::on<&cogui::key::L>::press = cogui::key::L;
cogui::key cogui::key::M( {cogui::events::key_class::key_m, false, false, false, L"m"} );
template<> cogui::key& cogui::on<&cogui::key::M>::press = cogui::key::M;
cogui::key cogui::key::N( {cogui::events::key_class::key_n, false, false, false, L"n"} );
template<> cogui::key& cogui::on<&cogui::key::N>::press = cogui::key::N;
cogui::key cogui::key::O( {cogui::events::key_class::key_o, false, false, false, L"o"} );
template<> cogui::key& cogui::on<&cogui::key::O>::press = cogui::key::O;
cogui::key cogui::key::P( {cogui::events::key_class::key_p, false, false, false, L"p"} );
template<> cogui::key& cogui::on<&cogui::key::P>::press = cogui::key::P;
cogui::key cogui::key::Q( {cogui::events::key_class::key_q, false, false, false, L"q"} );
template<> cogui::key& cogui::on<&cogui::key::Q>::press = cogui::key::Q;
cogui::key cogui::key::R( {cogui::events::key_class::key_r, false, false, false, L"r"} );
template<> cogui::key& cogui::on<&cogui::key::R>::press = cogui::key::R;
cogui::key cogui::key::S( {cogui::events::key_class::key_s, false, false, false, L"s"} );
template<> cogui::key& cogui::on<&cogui::key::S>::press = cogui::key::S;
cogui::key cogui::key::T( {cogui::events::key_class::key_t, false, false, false, L"t"} );
template<> cogui::key& cogui::on<&cogui::key::T>::press = cogui::key::T;
cogui::key cogui::key::U( {cogui::events::key_class::key_u, false, false, false, L"u"} );
template<> cogui::key& cogui::on<&cogui::key::U>::press = cogui::key::U;
cogui::key cogui::key::V( {cogui::events::key_class::key_v, false, false, false, L"v"} );
template<> cogui::key& cogui::on<&cogui::key::V>::press = cogui::key::V;
cogui::key cogui::key::W( {cogui::events::key_class::key_w, false, false, false, L"w"} );
template<> cogui::key& cogui::on<&cogui::key::W>::press = cogui::key::W;
cogui::key cogui::key::X( {cogui::events::key_class::key_x, false, false, false, L"x"} );
template<> cogui::key& cogui::on<&cogui::key::X>::press = cogui::key::X;
cogui::key cogui::key::Y( {cogui::events::key_class::key_y, false, false, false, L"y"} );
template<> cogui::key& cogui::on<&cogui::key::Y>::press = cogui::key::Y;
cogui::key cogui::key::Z( {cogui::events::key_class::key_z, false, false, false, L"z"} );
template<> cogui::key& cogui::on<&cogui::key::Z>::press = cogui::key::Z;
cogui::key cogui::key::Ctrl_Alt_F1( {cogui::events::key_class::key_f1, true, false, true, L"Ctrl-Alt-f1"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F1>::press = cogui::key::Ctrl_Alt_F1;
cogui::key cogui::key::Ctrl_Alt_F2( {cogui::events::key_class::key_f2, true, false, true, L"Ctrl-Alt-f2"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F2>::press = cogui::key::Ctrl_Alt_F2;
cogui::key cogui::key::Ctrl_Alt_F3( {cogui::events::key_class::key_f3, true, false, true, L"Ctrl-Alt-f3"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F3>::press = cogui::key::Ctrl_Alt_F3;
cogui::key cogui::key::Ctrl_Alt_F4( {cogui::events::key_class::key_f4, true, false, true, L"Ctrl-Alt-f4"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F4>::press = cogui::key::Ctrl_Alt_F4;
cogui::key cogui::key::Ctrl_Alt_F5( {cogui::events::key_class::key_f5, true, false, true, L"Ctrl-Alt-f5"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F5>::press = cogui::key::Ctrl_Alt_F5;
cogui::key cogui::key::Ctrl_Alt_F6( {cogui::events::key_class::key_f6, true, false, true, L"Ctrl-Alt-f6"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F6>::press = cogui::key::Ctrl_Alt_F6;
cogui::key cogui::key::Ctrl_Alt_F7( {cogui::events::key_class::key_f7, true, false, true, L"Ctrl-Alt-f7"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F7>::press = cogui::key::Ctrl_Alt_F7;
cogui::key cogui::key::Ctrl_Alt_F8( {cogui::events::key_class::key_f8, true, false, true, L"Ctrl-Alt-f8"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F8>::press = cogui::key::Ctrl_Alt_F8;
cogui::key cogui::key::Ctrl_Alt_F9( {cogui::events::key_class::key_f9, true, false, true, L"Ctrl-Alt-f9"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F9>::press = cogui::key::Ctrl_Alt_F9;
cogui::key cogui::key::Ctrl_Alt_F10( {cogui::events::key_class::key_f10, true, false, true, L"Ctrl-Alt-f10"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F10>::press = cogui::key::Ctrl_Alt_F10;
cogui::key cogui::key::Ctrl_Alt_F11( {cogui::events::key_class::key_f11, true, false, true, L"Ctrl-Alt-f11"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F11>::press = cogui::key::Ctrl_Alt_F11;
cogui::key cogui::key::Ctrl_Alt_F12( {cogui::events::key_class::key_f12, true, false, true, L"Ctrl-Alt-f12"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_F12>::press = cogui::key::Ctrl_Alt_F12;
cogui::key cogui::key::Alt_F1( {cogui::events::key_class::key_f1, true, false, false, L"Alt-f1"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F1>::press = cogui::key::Alt_F1;
cogui::key cogui::key::Alt_F2( {cogui::events::key_class::key_f2, true, false, false, L"Alt-f2"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F2>::press = cogui::key::Alt_F2;
cogui::key cogui::key::Alt_F3( {cogui::events::key_class::key_f3, true, false, false, L"Alt-f3"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F3>::press = cogui::key::Alt_F3;
cogui::key cogui::key::Alt_F4( {cogui::events::key_class::key_f4, true, false, false, L"Alt-f4"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F4>::press = cogui::key::Alt_F4;
cogui::key cogui::key::Alt_F5( {cogui::events::key_class::key_f5, true, false, false, L"Alt-f5"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F5>::press = cogui::key::Alt_F5;
cogui::key cogui::key::Alt_F6( {cogui::events::key_class::key_f6, true, false, false, L"Alt-f6"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F6>::press = cogui::key::Alt_F6;
cogui::key cogui::key::Alt_F7( {cogui::events::key_class::key_f7, true, false, false, L"Alt-f7"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F7>::press = cogui::key::Alt_F7;
cogui::key cogui::key::Alt_F8( {cogui::events::key_class::key_f8, true, false, false, L"Alt-f8"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F8>::press = cogui::key::Alt_F8;
cogui::key cogui::key::Alt_F9( {cogui::events::key_class::key_f9, true, false, false, L"Alt-f9"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F9>::press = cogui::key::Alt_F9;
cogui::key cogui::key::Alt_F10( {cogui::events::key_class::key_f10, true, false, false, L"Alt-f10"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F10>::press = cogui::key::Alt_F10;
cogui::key cogui::key::Alt_F11( {cogui::events::key_class::key_f11, true, false, false, L"Alt-f11"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F11>::press = cogui::key::Alt_F11;
cogui::key cogui::key::Alt_F12( {cogui::events::key_class::key_f12, true, false, false, L"Alt-f12"} );
template<> cogui::key& cogui::on<&cogui::key::Alt_F12>::press = cogui::key::Alt_F12;
cogui::key cogui::key::Ctrl_F1( {cogui::events::key_class::key_f1, false, false, true, L"Ctrl-f1"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F1>::press = cogui::key::Ctrl_F1;
cogui::key cogui::key::Ctrl_F2( {cogui::events::key_class::key_f2, false, false, true, L"Ctrl-f2"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F2>::press = cogui::key::Ctrl_F2;
cogui::key cogui::key::Ctrl_F3( {cogui::events::key_class::key_f3, false, false, true, L"Ctrl-f3"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F3>::press = cogui::key::Ctrl_F3;
cogui::key cogui::key::Ctrl_F4( {cogui::events::key_class::key_f4, false, false, true, L"Ctrl-f4"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F4>::press = cogui::key::Ctrl_F4;
cogui::key cogui::key::Ctrl_F5( {cogui::events::key_class::key_f5, false, false, true, L"Ctrl-f5"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F5>::press = cogui::key::Ctrl_F5;
cogui::key cogui::key::Ctrl_F6( {cogui::events::key_class::key_f6, false, false, true, L"Ctrl-f6"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F6>::press = cogui::key::Ctrl_F6;
cogui::key cogui::key::Ctrl_F7( {cogui::events::key_class::key_f7, false, false, true, L"Ctrl-f7"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F7>::press = cogui::key::Ctrl_F7;
cogui::key cogui::key::Ctrl_F8( {cogui::events::key_class::key_f8, false, false, true, L"Ctrl-f8"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F8>::press = cogui::key::Ctrl_F8;
cogui::key cogui::key::Ctrl_F9( {cogui::events::key_class::key_f9, false, false, true, L"Ctrl-f9"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F9>::press = cogui::key::Ctrl_F9;
cogui::key cogui::key::Ctrl_F10( {cogui::events::key_class::key_f10, false, false, true, L"Ctrl-f10"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F10>::press = cogui::key::Ctrl_F10;
cogui::key cogui::key::Ctrl_F11( {cogui::events::key_class::key_f11, false, false, true, L"Ctrl-f11"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F11>::press = cogui::key::Ctrl_F11;
cogui::key cogui::key::Ctrl_F12( {cogui::events::key_class::key_f12, false, false, true, L"Ctrl-f12"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_F12>::press = cogui::key::Ctrl_F12;
cogui::key cogui::key::F1( {cogui::events::key_class::key_f1, false, false, false, L"f1"} );
template<> cogui::key& cogui::on<&cogui::key::F1>::press = cogui::key::F1;
cogui::key cogui::key::F2( {cogui::events::key_class::key_f2, false, false, false, L"f2"} );
template<> cogui::key& cogui::on<&cogui::key::F2>::press = cogui::key::F2;
cogui::key cogui::key::F3( {cogui::events::key_class::key_f3, false, false, false, L"f3"} );
template<> cogui::key& cogui::on<&cogui::key::F3>::press = cogui::key::F3;
cogui::key cogui::key::F4( {cogui::events::key_class::key_f4, false, false, false, L"f4"} );
template<> cogui::key& cogui::on<&cogui::key::F4>::press = cogui::key::F4;
cogui::key cogui::key::F5( {cogui::events::key_class::key_f5, false, false, false, L"f5"} );
template<> cogui::key& cogui::on<&cogui::key::F5>::press = cogui::key::F5;
cogui::key cogui::key::F6( {cogui::events::key_class::key_f6, false, false, false, L"f6"} );
template<> cogui::key& cogui::on<&cogui::key::F6>::press = cogui::key::F6;
cogui::key cogui::key::F7( {cogui::events::key_class::key_f7, false, false, false, L"f7"} );
template<> cogui::key& cogui::on<&cogui::key::F7>::press = cogui::key::F7;
cogui::key cogui::key::F8( {cogui::events::key_class::key_f8, false, false, false, L"f8"} );
template<> cogui::key& cogui::on<&cogui::key::F8>::press = cogui::key::F8;
cogui::key cogui::key::F9( {cogui::events::key_class::key_f9, false, false, false, L"f9"} );
template<> cogui::key& cogui::on<&cogui::key::F9>::press = cogui::key::F9;
cogui::key cogui::key::F10( {cogui::events::key_class::key_f10, false, false, false, L"f10"} );
template<> cogui::key& cogui::on<&cogui::key::F10>::press = cogui::key::F10;
cogui::key cogui::key::F11( {cogui::events::key_class::key_f11, false, false, false, L"f11"} );
template<> cogui::key& cogui::on<&cogui::key::F11>::press = cogui::key::F11;
cogui::key cogui::key::F12( {cogui::events::key_class::key_f12, false, false, false, L"f12"} );
template<> cogui::key& cogui::on<&cogui::key::F12>::press = cogui::key::F12;

cogui::key cogui::key::Ctrl_Alt_Shift_F1( {cogui::events::key_class::key_f1, true, true, true, L"Ctrl-Alt-f1"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F1>::press = cogui::key::Ctrl_Alt_Shift_F1;
cogui::key cogui::key::Ctrl_Alt_Shift_F2( {cogui::events::key_class::key_f2, true, true, true, L"Ctrl-Alt-f2"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F2>::press = cogui::key::Ctrl_Alt_Shift_F2;
cogui::key cogui::key::Ctrl_Alt_Shift_F3( {cogui::events::key_class::key_f3, true, true, true, L"Ctrl-Alt-f3"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F3>::press = cogui::key::Ctrl_Alt_Shift_F3;
cogui::key cogui::key::Ctrl_Alt_Shift_F4( {cogui::events::key_class::key_f4, true, true, true, L"Ctrl-Alt-f4"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F4>::press = cogui::key::Ctrl_Alt_Shift_F4;
cogui::key cogui::key::Ctrl_Alt_Shift_F5( {cogui::events::key_class::key_f5, true, true, true, L"Ctrl-Alt-f5"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F5>::press = cogui::key::Ctrl_Alt_Shift_F5;
cogui::key cogui::key::Ctrl_Alt_Shift_F6( {cogui::events::key_class::key_f6, true, true, true, L"Ctrl-Alt-f6"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F6>::press = cogui::key::Ctrl_Alt_Shift_F6;
cogui::key cogui::key::Ctrl_Alt_Shift_F7( {cogui::events::key_class::key_f7, true, true, true, L"Ctrl-Alt-f7"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F7>::press = cogui::key::Ctrl_Alt_Shift_F7;
cogui::key cogui::key::Ctrl_Alt_Shift_F8( {cogui::events::key_class::key_f8, true, true, true, L"Ctrl-Alt-f8"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F8>::press = cogui::key::Ctrl_Alt_Shift_F8;
cogui::key cogui::key::Ctrl_Alt_Shift_F9( {cogui::events::key_class::key_f9, true, true, true, L"Ctrl-Alt-f9"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F9>::press = cogui::key::Ctrl_Alt_Shift_F9;
cogui::key cogui::key::Ctrl_Alt_Shift_F10( {cogui::events::key_class::key_f10, true, true, true, L"Ctrl-Alt-f10"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F10>::press = cogui::key::Ctrl_Alt_Shift_F10;
cogui::key cogui::key::Ctrl_Alt_Shift_F11( {cogui::events::key_class::key_f11, true, true, true, L"Ctrl-Alt-f11"} );
template<> cogui::key& cogui::on<&cogui::key::Ctrl_Alt_Shift_F11>::press = cogui::key::Ctrl_Alt_Shift_F11;
cogui::key cogui::key::Ctrl_Alt_Shift_F12( {cogui::events::key_class::key_f12, true, true, true, L"Ctrl-Alt-f12"} );


cogui::key::key(const cogui::events::keypress &generator): m_generator(generator)
{
}

cogui::key cogui::key::operator +(const cogui::key &other)
{

    // we can create a hotkey only if one of the keys is a modifier
    if(m_generator.get_type() != cogui::events::key_class::key_modifier && other.m_generator.get_type() != cogui::events::key_class::key_modifier)
    {
        throw "Cannot create a hotkey with this combination";
    }

    key result;
    result.m_generator.set_alt_modifier(m_generator.get_alt() || other.m_generator.get_alt());
    result.m_generator.set_ctrl_modifier(m_generator.get_ctrl() || other.m_generator.get_ctrl());
    result.m_generator.set_shift_modifier(m_generator.get_shift() || other.m_generator.get_shift());

    if(m_generator.get_type() != cogui::events::key_class::key_modifier)
    {
        result.m_generator.set_chardata(m_generator.get_chardata());
        result.m_generator.set_type(m_generator.get_type());
    }
    else
    if(other.m_generator.get_type() != cogui::events::key_class::key_modifier)
    {
        result.m_generator.set_chardata(other.m_generator.get_chardata());
        result.m_generator.set_type(other.m_generator.get_type());
    }
    else
    {
        result.m_generator.set_type(cogui::events::key_class::key_modifier);
    }

    result.m_generator.set_as_hotkey();

    return result;
}
